### ISSUE TITLE
License(?)

### ISSUE THREAD

**Issue by Ryan-DowlingSoka** [A57R4L/SceneViewExtTest#1]
Hi! this seems like great work. Something I was wondering was if you had consider adding a license to this repo?

You have copyright notices on your files, but don't prescribe what license you would like this work to be used.

Its obviously 100% up to you which one you choose, but I like the MIT one for its simplicity if your intention is to share this code fully and completely. If not, I think there are some other many great options-> Clarity is really the thing I'm hoping for. :)

**Comment by A57R4L** [comment]
Thank you for pointing this out and thank you for the feedback! I haven't thought about this before, but makes perfect sense to add a license to this.

Original intention was to have this like a additional documentation to help understand how the engine works, but could of course be used as a boilerplate to build own SceneViewExtension or bring custom shaders to a project.

I think MIT license would definitely make sense. I'll probably need to tidy the code up a bit from a few engine references to be confident to release this under a license but I should be able to do that quite soon. Thank you again for a very good suggestion.

**Comment by A57R4L** [comment]
Sorry, this took longer than expected, but you can now find a rework of this at a completely new repository: [https://github.com/A57R4L/SceneViewExtensionTemplate](https://github.com/A57R4L/SceneViewExtensionTemplate)

There are some changes in the engine codebase, but it should be quite easily be ported back to 4.26 & 4.27 by referencing this legacy repository. Wanted to keep the new repository just for UE5 for the sake of clarity in the codebase.

As it is now a complete rewrite, the new one is release under MIT license.
